"""init: topology_changelog

Revision ID: 04bed2ef6986
Revises: 
Create Date: 2026-05-11 00:21:32.477288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bed2ef6986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology_changelog',
    sa.Column('change_id', sa.CHAR(length=36), nullable=False, comment='UUID (hex 32位，无连字符)'),
    sa.Column('operation', sa.Enum('ADD', 'DELETE', 'MODIFY', name='topology_operation_enum'), nullable=False, comment='链路操作类型'),
    sa.Column('src_device', sa.String(length=23), nullable=True, comment='源交换机 DPID (16位 hex)'),
    sa.Column('src_port', sa.String(length=32), nullable=True, comment='源端口号'),
    sa.Column('dst_device', sa.String(length=23), nullable=True, comment='目的交换机 DPID (16位 hex)'),
    sa.Column('dst_port', sa.String(length=32), nullable=True, comment='目的端口号'),
    sa.Column('topology_version', sa.BigInteger(), nullable=True, comment='拓扑版本号'),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='变更时间'),
    sa.PrimaryKeyConstraint('change_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ts', 'topology_changelog', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ts', table_name='topology_changelog')
    op.drop_table('topology_changelog')
    # ### end Alembic commands ###
