"""add perf_history table

Revision ID: f94e85c3dd60
Revises: 04bed2ef6986
Create Date: 2026-05-11 01:09:38.921342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94e85c3dd60'
down_revision: Union[str, Sequence[str], None] = '04bed2ef6986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perf_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID（配合分区键）'),
    sa.Column('link_id', sa.String(length=64), nullable=False, comment='链路标识: src_dpid:src_port→dst_dpid:dst_port'),
    sa.Column('throughput', sa.Float(), nullable=True, comment='吞吐量 (bps)'),
    sa.Column('delay', sa.Float(), nullable=True, comment='时延 (ms)'),
    sa.Column('jitter', sa.Float(), nullable=True, comment='抖动 (ms)'),
    sa.Column('packet_loss', sa.Float(), nullable=True, comment='丢包率 (%)'),
    sa.Column('congestion_level', sa.Integer(), nullable=True, comment='拥堵等级 0=NORMAL 1=MILD 2=MODERATE 3=SEVERE'),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='采样时间'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='pk_perf_history'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_link_time', 'perf_history', ['link_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_link_time', table_name='perf_history')
    op.drop_table('perf_history')
    # ### end Alembic commands ###
